//! IVC Accumulator — Groth16 recursive verifier for FL round proofs.
//!
//! ## Fixes in this version
//!
//! ### Fix 2: Persistent IVC VK (Critical)
//! The IVC summary circuit's trusted setup is done ONCE and the VK is
//! persisted to `ivc_vk.bin` + `ivc_pk.bin`.  Subsequent `accumulate` calls
//! load these keys from disk.  The VK is public and can be pinned on-chain,
//! so anyone can verify the IVC proof independently.
//!
//! ### Fix 6: N-independent circuit (Significant)
//! The circuit is padded to a fixed capacity `MAX_ROUNDS = 64`.  All
//! witnesses beyond the actual N rounds are filled with zero-value
//! "dummy" records that satisfy every constraint trivially.  The constraint
//! structure is completely fixed regardless of N:
//!
//!   • Hash chain: enforce new_hash[i] == prev_hash[i+1] for ALL MAX_ROUNDS-1
//!     pairs — dummy slots satisfy this trivially (both are Fr::zero()).
//!   • Final hash: a private selector vector `sel[0..MAX_ROUNDS]` with
//!     exactly one bit set at position n-1 selects the last real new_hash.
//!     Constraints: each sel[i] ∈ {0,1}, Σsel[i] == 1,
//!     Σ(sel[i] * new_hash[i]) == final_hash.
//!   • Proof chain hash: Poseidon over all MAX_ROUNDS commits (always fixed).
//!
//! This means one trusted setup covers any N ≤ MAX_ROUNDS.
//!
//! ## Security model
//!
//! The summary proof is NOT a full recursive SNARK (no in-circuit Groth16
//! pairing check — that requires a Pasta/BLS12-381 cycle).  Instead it
//! proves hash-chain integrity via Poseidon:
//!   - Forging any round breaks the Poseidon chain hash.
//!   - Forging the summary proof requires breaking Groth16 soundness.
//! The VK is now fixed and public, so a fresh VK cannot be generated by a
//! malicious prover (Fix 2).

use ark_bn254::{Bn254, Fr};
use ark_crypto_primitives::sponge::{
    poseidon::PoseidonSponge, CryptographicSponge,
};
use ark_ff::PrimeField;
use ark_groth16::{prepare_verifying_key, Groth16, ProvingKey, VerifyingKey};
use ark_r1cs_std::{
    alloc::AllocVar,
    eq::EqGadget,
    fields::{fp::FpVar, FieldVar},
};
use ark_relations::r1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use super::fl_round_circuit::{poseidon_config, poseidon_hash_native};
use super::round_prover::{fr_to_bytes, FLProof, FLRoundProver};

// ─── Capacity constant ────────────────────────────────────────────────────────

/// Maximum number of rounds the IVC circuit supports.
/// The circuit is always padded to exactly this many slots (Fix 6).
/// One trusted setup serves any N ≤ MAX_ROUNDS.
/// Bump this value (and re-run `ivc-setup`) to support longer training runs.
pub const MAX_ROUNDS: usize = 64;

// ─── Per-round record ─────────────────────────────────────────────────────────

#[derive(Clone, Debug)]
struct RoundRecord {
    prev_hash_fr:     Fr,
    new_hash_fr:      Fr,
    proof_commitment: Fr, // Poseidon over proof_bytes chunks
}

impl RoundRecord {
    fn dummy_with_hash(filler: Fr) -> Self {
        RoundRecord {
            prev_hash_fr:     filler,
            new_hash_fr:      filler,
            proof_commitment: Fr::from(0u64),
        }
    }
}

// ─── IVC Summary Circuit ──────────────────────────────────────────────────────

/// R1CS circuit that proves the integrity of up to MAX_ROUNDS FL round proofs.
///
/// Circuit is always MAX_ROUNDS slots wide (Fix 6 — N-independent structure).
/// Actual rounds n ≤ MAX_ROUNDS; slots n..MAX_ROUNDS are dummy (zero hashes).
///
/// Public inputs (4):
///   [initial_model_hash, final_model_hash, total_rounds, proof_chain_hash]
///
/// Private witnesses (MAX_ROUNDS × 4):
///   [prev_hash[0..MAX], new_hash[0..MAX], proof_commit[0..MAX],
///    sel[0..MAX]]   ← selector: sel[n-1]=1, rest=0
///
/// Constraints (FIXED regardless of n — same structure for any N ≤ MAX):
///   1. initial_hash == prev_hash[0]
///   2. For ALL i in 0..MAX_ROUNDS-1: new_hash[i] == prev_hash[i+1]
///      (dummy slots: prev=new=0, satisfied trivially)
///   3. Each sel[i] ∈ {0,1}:  sel[i] * (sel[i] - 1) == 0
///   4. Σ sel[i] == 1  (exactly one selector is set)
///   5. Σ (sel[i] * new_hash[i]) == final_hash  (selects last real slot)
///   6. proof_chain_hash == Poseidon(commit[0], …, commit[MAX_ROUNDS−1])
///      (dummy slots contribute commit=0)
///   total_rounds is a public input (verifier checks N independently).
#[derive(Clone, Debug)]
struct IVCSummaryCircuit {
    // Public
    initial_model_hash: Fr,
    final_model_hash:   Fr,
    total_rounds:       u64,         // actual n ≤ MAX_ROUNDS
    proof_chain_hash:   Fr,
    // Private — always MAX_ROUNDS entries (dummy-padded)
    records:            Vec<RoundRecord>,
    poseidon_cfg: ark_crypto_primitives::sponge::poseidon::PoseidonConfig<Fr>,
}

impl IVCSummaryCircuit {
    /// Build the blank circuit used for trusted setup.
    /// Uses total_rounds=1 and all-dummy records; the selector for slot 0 = 1.
    fn blank(cfg: ark_crypto_primitives::sponge::poseidon::PoseidonConfig<Fr>) -> Self {
        // In the blank circuit, all slots are dummy with hash=0 and sel[0]=1.
        // The chain constraint requires new_hash[i] == prev_hash[i+1] for all i;
        // with all hashes = 0 this is trivially satisfied.
        // final_model_hash = 0 == new_hash[0] = 0 (selected by sel[0]=1). ✓
        IVCSummaryCircuit {
            initial_model_hash: Fr::from(0u64),
            final_model_hash:   Fr::from(0u64),
            total_rounds:       1,
            proof_chain_hash:   Fr::from(0u64),
            records:            vec![RoundRecord::dummy_with_hash(Fr::from(0u64)); MAX_ROUNDS],
            poseidon_cfg:       cfg,
        }
    }
}

impl ConstraintSynthesizer<Fr> for IVCSummaryCircuit {
    fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
        use ark_crypto_primitives::sponge::constraints::CryptographicSpongeVar;
        use ark_crypto_primitives::sponge::poseidon::constraints::PoseidonSpongeVar;

        // ── Public inputs ─────────────────────────────────────────────────
        let init_hash_var    = FpVar::<Fr>::new_input(cs.clone(), || Ok(self.initial_model_hash))?;
        let final_hash_var   = FpVar::<Fr>::new_input(cs.clone(), || Ok(self.final_model_hash))?;
        let total_rounds_var = FpVar::<Fr>::new_input(cs.clone(), || Ok(Fr::from(self.total_rounds)))?;
        let chain_hash_var   = FpVar::<Fr>::new_input(cs.clone(), || Ok(self.proof_chain_hash))?;
        // total_rounds is exposed as a public input so the verifier can
        // check the range [1, MAX_ROUNDS] independently.
        let _ = total_rounds_var;

        // ── Private witnesses — always exactly MAX_ROUNDS slots ───────────
        // Dummy slots have prev=new=commit=Fr::zero(), sel=0.
        let mut prev_hash_vars:    Vec<FpVar<Fr>> = Vec::with_capacity(MAX_ROUNDS);
        let mut new_hash_vars:     Vec<FpVar<Fr>> = Vec::with_capacity(MAX_ROUNDS);
        let mut proof_commit_vars: Vec<FpVar<Fr>> = Vec::with_capacity(MAX_ROUNDS);
        // selector[i] = 1 if i == n-1 (last real slot), else 0.
        // This is a private witness — the constraint system enforces its
        // correctness via the bit-check and sum-to-one constraints below.
        let mut sel_vars:          Vec<FpVar<Fr>> = Vec::with_capacity(MAX_ROUNDS);

        let n = self.total_rounds as usize;
        for (i, rec) in self.records.iter().enumerate() {
            prev_hash_vars.push(   FpVar::new_witness(cs.clone(), || Ok(rec.prev_hash_fr))?);
            new_hash_vars.push(    FpVar::new_witness(cs.clone(), || Ok(rec.new_hash_fr))?);
            proof_commit_vars.push(FpVar::new_witness(cs.clone(), || Ok(rec.proof_commitment))?);
            // sel[i] = 1 iff i == n-1, else 0.
            let sel_val = if n > 0 && i == n - 1 { Fr::from(1u64) } else { Fr::from(0u64) };
            sel_vars.push(FpVar::new_witness(cs.clone(), || Ok(sel_val))?);
        }

        // ── Constraint 1: initial_hash == prev_hash[0] ───────────────────
        init_hash_var.enforce_equal(&prev_hash_vars[0])?;

        // ── Constraint 2: hash chain for ALL MAX_ROUNDS-1 pairs (FIXED) ──
        // new_hash[i] == prev_hash[i+1] for ALL i in 0..MAX_ROUNDS-1.
        // Dummy slots have new=prev=Fr::zero() so this is trivially satisfied.
        // The number of these constraints is always MAX_ROUNDS-1, independent of n.
        for i in 0..(MAX_ROUNDS - 1) {
            new_hash_vars[i].enforce_equal(&prev_hash_vars[i + 1])?;
        }

        // ── Constraint 3: each sel[i] ∈ {0,1} ───────────────────────────
        // sel[i] * (sel[i] - 1) == 0
        let one = FpVar::<Fr>::constant(Fr::from(1u64));
        for sv in &sel_vars {
            let sv_minus_one = sv - &one;
            sv.mul_equals(&sv_minus_one, &FpVar::zero())?;
        }

        // ── Constraint 4: Σ sel[i] == 1  (exactly one selector set) ─────
        let sum_sel = sel_vars.iter()
            .skip(1)
            .fold(sel_vars[0].clone(), |acc, sv| acc + sv);
        sum_sel.enforce_equal(&one)?;

        // ── Constraint 5: Σ (sel[i] * new_hash[i]) == final_hash ────────
        // Selects new_hash[n-1] without branching on n.
        let selected = sel_vars.iter().zip(new_hash_vars.iter())
            .map(|(s, h)| s * h)
            .fold(FpVar::zero(), |acc, t| acc + t);
        selected.enforce_equal(&final_hash_var)?;

        // ── Constraint 6: proof_chain_hash = Poseidon(commit[0..MAX]) ───
        // Fixed MAX_ROUNDS inputs — structure never changes regardless of n.
        let mut sponge = PoseidonSpongeVar::<Fr>::new(cs.clone(), &self.poseidon_cfg);
        for cv in &proof_commit_vars {
            sponge.absorb(cv)?;
        }
        let squeezed = sponge.squeeze_field_elements(1)?;
        chain_hash_var.enforce_equal(&squeezed[0])?;

        Ok(())
    }
}

// ─── IVC Keys ─────────────────────────────────────────────────────────────────

/// Persisted IVC keys (Fix 2).
pub struct IVCKeys {
    pk:  ProvingKey<Bn254>,
    pub vk: VerifyingKey<Bn254>,
}

impl IVCKeys {
    /// Generate and save IVC keys.  Call once; persist the files.
    pub fn setup_and_save(keys_dir: &Path) -> Result<Self, String> {
        std::fs::create_dir_all(keys_dir)
            .map_err(|e| format!("Create IVC keys dir: {}", e))?;
        let cfg = poseidon_config();
        let blank = IVCSummaryCircuit::blank(cfg);
        let mut rng = OsRng;
        let (pk, vk) = Groth16::<Bn254>::circuit_specific_setup(blank, &mut rng)
            .map_err(|e| format!("IVC setup: {:?}", e))?;

        let pk_path = keys_dir.join("ivc_pk.bin");
        let vk_path = keys_dir.join("ivc_vk.bin");

        let mut pk_buf = Vec::new();
        pk.serialize_compressed(&mut pk_buf)
            .map_err(|e| format!("IVC PK serialize: {:?}", e))?;
        std::fs::write(&pk_path, &pk_buf)
            .map_err(|e| format!("IVC PK write: {}", e))?;

        let mut vk_buf = Vec::new();
        vk.serialize_compressed(&mut vk_buf)
            .map_err(|e| format!("IVC VK serialize: {:?}", e))?;
        std::fs::write(&vk_path, &vk_buf)
            .map_err(|e| format!("IVC VK write: {}", e))?;

        println!("IVC keys saved → ivc_pk.bin ({} KB), ivc_vk.bin ({} B)",
            pk_buf.len() / 1024, vk_buf.len());

        Ok(IVCKeys { pk, vk })
    }

    /// Load persisted IVC keys.
    pub fn load(keys_dir: &Path) -> Result<Self, String> {
        let pk_path = keys_dir.join("ivc_pk.bin");
        let vk_path = keys_dir.join("ivc_vk.bin");

        let pk_bytes = std::fs::read(&pk_path)
            .map_err(|e| format!("IVC PK read: {}", e))?;
        let pk = ProvingKey::<Bn254>::deserialize_compressed(pk_bytes.as_slice())
            .map_err(|e| format!("IVC PK deser: {:?}", e))?;

        let vk_bytes = std::fs::read(&vk_path)
            .map_err(|e| format!("IVC VK read: {}", e))?;
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(vk_bytes.as_slice())
            .map_err(|e| format!("IVC VK deser: {:?}", e))?;

        Ok(IVCKeys { pk, vk })
    }

    pub fn vk_hex(&self) -> String {
        let mut buf = Vec::new();
        self.vk.serialize_compressed(&mut buf).unwrap();
        hex::encode(&buf)
    }
}

// ─── IVC State ────────────────────────────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct IVCState {
    pub round:                u64,
    pub initial_model_hash:   String, // Fr bytes, hex
    pub proof_chain:          Vec<FLProof>,
}

impl IVCState {
    pub fn new(initial_model_hash_fr: &Fr) -> Self {
        IVCState {
            round: 0,
            initial_model_hash: hex::encode(fr_to_bytes(initial_model_hash_fr)),
            proof_chain: Vec::new(),
        }
    }

    /// Fold one round proof into the accumulator.
    pub fn fold_round(&mut self, proof: FLProof) -> Result<(), String> {
        if self.proof_chain.len() >= MAX_ROUNDS {
            return Err(format!(
                "Exceeded MAX_ROUNDS ({}). Bump MAX_ROUNDS and re-run ivc-setup.",
                MAX_ROUNDS
            ));
        }

        // Verify the round's Groth16 proof before accepting it.
        let valid = FLRoundProver::verify_proof(&proof)
            .map_err(|e| format!("fold_round verify: {}", e))?;
        if !valid {
            return Err(format!("Round {} Groth16 proof is invalid", proof.round_id));
        }

        // Check round-id continuity.
        if proof.round_id != self.round {
            return Err(format!("Expected round {}, got {}", self.round, proof.round_id));
        }

        // Check hash-chain continuity.
        if let Some(last) = self.proof_chain.last() {
            if proof.prev_model_hash != last.new_model_hash {
                return Err(format!(
                    "Hash chain break at round {}: expected prev={}…, got {}…",
                    proof.round_id,
                    &last.new_model_hash[..16],
                    &proof.prev_model_hash[..16],
                ));
            }
        }

        self.proof_chain.push(proof);
        self.round += 1;
        Ok(())
    }

    /// Produce the final IVC proof using persisted keys.
    ///
    /// `keys_dir` must contain `ivc_pk.bin` and `ivc_vk.bin` (written by
    /// `IVCKeys::setup_and_save` or the `ivc-setup` CLI command).
    pub fn finalize(&self, keys_dir: &Path) -> Result<FinalIVCProof, String> {
        if self.proof_chain.is_empty() {
            return Err("No rounds accumulated".to_string());
        }

        let keys = IVCKeys::load(keys_dir)
            .map_err(|e| format!("Load IVC keys: {}", e))?;

        self.finalize_with_keys(&keys)
    }

    /// Internal finalize with already-loaded keys.
    pub fn finalize_with_keys(&self, keys: &IVCKeys) -> Result<FinalIVCProof, String> {
        let cfg = poseidon_config();
        let n   = self.proof_chain.len();

        // Build real records for rounds 0..n, dummy records for n..MAX_ROUNDS.
        // Dummy slots must have prev_hash == new_hash == final_model_hash so that
        // the chain constraint (new_hash[i] == prev_hash[i+1] for ALL i) is satisfied.
        let initial_model_hash = self.decode_initial_hash()?;
        let real_records = self.build_records()?;
        let final_model_hash = real_records[n - 1].new_hash_fr;

        // Pad to MAX_ROUNDS with dummy entries carrying the final hash.
        let mut records = real_records;
        while records.len() < MAX_ROUNDS {
            records.push(RoundRecord::dummy_with_hash(final_model_hash));
        }

        // proof_chain_hash = Poseidon over ALL MAX_ROUNDS commits (including dummies).
        // Dummy commits are Fr::zero() regardless of the filler hash.
        let commits: Vec<Fr> = records.iter().map(|r| r.proof_commitment).collect();
        let proof_chain_hash = {
            let mut sponge = PoseidonSponge::<Fr>::new(&cfg);
            for c in &commits {
                sponge.absorb(c);
            }
            sponge.squeeze_field_elements::<Fr>(1)[0]
        };

        let circuit = IVCSummaryCircuit {
            initial_model_hash,
            final_model_hash,
            total_rounds: n as u64,
            proof_chain_hash,
            records,
            poseidon_cfg: cfg,
        };

        let mut rng = OsRng;
        let proof = Groth16::<Bn254>::prove(&keys.pk, circuit, &mut rng)
            .map_err(|e| format!("IVC prove: {:?}", e))?;

        let mut proof_bytes = Vec::new();
        proof.serialize_compressed(&mut proof_bytes)
            .map_err(|e| format!("IVC proof serialize: {:?}", e))?;

        let mut vk_bytes_buf = Vec::new();
        keys.vk.serialize_compressed(&mut vk_bytes_buf)
            .map_err(|e| format!("IVC VK serialize: {:?}", e))?;

        let on_chain_anchor = poseidon_hash_native(&[
            initial_model_hash,
            final_model_hash,
            Fr::from(n as u64),
            proof_chain_hash,
        ]);

        Ok(FinalIVCProof {
            total_rounds:       n as u64,
            initial_model_hash: hex::encode(fr_to_bytes(&initial_model_hash)),
            final_model_hash:   hex::encode(fr_to_bytes(&final_model_hash)),
            proof_chain_hash:   hex::encode(fr_to_bytes(&proof_chain_hash)),
            on_chain_anchor:    hex::encode(fr_to_bytes(&on_chain_anchor)),
            ivc_proof_bytes:    hex::encode(&proof_bytes),
            ivc_vk_bytes:       hex::encode(&vk_bytes_buf),
            last_round_proof:   self.proof_chain.last().unwrap().clone(),
        })
    }

    // ── Internal helpers ──────────────────────────────────────────────────

    pub fn decode_initial_hash(&self) -> Result<Fr, String> {
        let bytes = hex::decode(&self.initial_model_hash)
            .map_err(|e| format!("initial_hash hex: {}", e))?;
        Fr::deserialize_compressed(bytes.as_slice())
            .map_err(|e| format!("initial_hash Fr: {:?}", e))
    }

    /// Build the real round records (no padding — caller adds padding).
    fn build_records(&self) -> Result<Vec<RoundRecord>, String> {
        let cfg = poseidon_config();
        let mut records = Vec::with_capacity(self.proof_chain.len());

        for proof in &self.proof_chain {
            let prev_bytes = hex::decode(&proof.prev_model_hash)
                .map_err(|e| format!("prev_hash hex: {}", e))?;
            let new_bytes  = hex::decode(&proof.new_model_hash)
                .map_err(|e| format!("new_hash hex: {}", e))?;

            let prev_hash_fr = Fr::deserialize_compressed(prev_bytes.as_slice())
                .map_err(|e| format!("prev_hash Fr: {:?}", e))?;
            let new_hash_fr  = Fr::deserialize_compressed(new_bytes.as_slice())
                .map_err(|e| format!("new_hash Fr: {:?}", e))?;

            let proof_raw = hex::decode(&proof.proof_bytes)
                .map_err(|e| format!("proof_bytes hex: {}", e))?;
            let proof_commitment = proof_bytes_to_field_commitment(&proof_raw, &cfg);

            records.push(RoundRecord {
                prev_hash_fr,
                new_hash_fr,
                proof_commitment,
            });
        }
        Ok(records)
    }
}

/// Map raw proof bytes → Fr via Poseidon of 4-byte chunks.
fn proof_bytes_to_field_commitment(
    bytes: &[u8],
    cfg:   &ark_crypto_primitives::sponge::poseidon::PoseidonConfig<Fr>,
) -> Fr {
    let chunks: Vec<Fr> = bytes.chunks(4).map(|c| {
        let mut buf = [0u8; 4];
        buf[..c.len()].copy_from_slice(c);
        Fr::from(u32::from_le_bytes(buf) as u64)
    }).collect();

    let mut sponge = PoseidonSponge::<Fr>::new(cfg);
    for chunk in &chunks {
        sponge.absorb(chunk);
    }
    sponge.squeeze_field_elements::<Fr>(1)[0]
}

// ─── Final IVC Proof ──────────────────────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FinalIVCProof {
    pub total_rounds:       u64,
    pub initial_model_hash: String,
    pub final_model_hash:   String,
    pub proof_chain_hash:   String,
    pub on_chain_anchor:    String,
    pub ivc_proof_bytes:    String, // 128 bytes, O(1) regardless of N
    pub ivc_vk_bytes:       String, // public, pinnable on-chain
    pub last_round_proof:   FLProof,
}

impl FinalIVCProof {
    /// Verify the Groth16 IVC summary proof against the embedded VK.
    ///
    /// For production use, the verifier should load `ivc_vk.bin` from the
    /// pinned on-chain anchor and verify against that, not the VK embedded
    /// here (which the prover also wrote).
    pub fn verify(&self) -> Result<bool, String> {
        let vk_bytes = hex::decode(&self.ivc_vk_bytes)
            .map_err(|e| format!("VK hex: {}", e))?;
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(vk_bytes.as_slice())
            .map_err(|e| format!("VK deser: {:?}", e))?;
        let pvk = prepare_verifying_key(&vk);

        let proof_bytes = hex::decode(&self.ivc_proof_bytes)
            .map_err(|e| format!("proof hex: {}", e))?;
        let proof = ark_groth16::Proof::<Bn254>::deserialize_compressed(proof_bytes.as_slice())
            .map_err(|e| format!("proof deser: {:?}", e))?;

        let init_fr  = Fr::deserialize_compressed(hex::decode(&self.initial_model_hash)
            .map_err(|e| format!("init hex: {}", e))?.as_slice())
            .map_err(|e| format!("init Fr: {:?}", e))?;
        let final_fr = Fr::deserialize_compressed(hex::decode(&self.final_model_hash)
            .map_err(|e| format!("final hex: {}", e))?.as_slice())
            .map_err(|e| format!("final Fr: {:?}", e))?;
        let chain_fr = Fr::deserialize_compressed(hex::decode(&self.proof_chain_hash)
            .map_err(|e| format!("chain hex: {}", e))?.as_slice())
            .map_err(|e| format!("chain Fr: {:?}", e))?;

        let public_inputs = vec![init_fr, final_fr, Fr::from(self.total_rounds), chain_fr];

        Groth16::<Bn254>::verify_with_processed_vk(&pvk, &public_inputs, &proof)
            .map_err(|e| format!("Groth16 IVC verify: {:?}", e))
    }

    /// Verify using a pinned external VK (the one that was saved to ivc_vk.bin).
    /// Use this in production — it does NOT trust the embedded VK.
    pub fn verify_with_pinned_vk(&self, pinned_vk_hex: &str) -> Result<bool, String> {
        let vk_bytes = hex::decode(pinned_vk_hex)
            .map_err(|e| format!("pinned VK hex: {}", e))?;
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(vk_bytes.as_slice())
            .map_err(|e| format!("pinned VK deser: {:?}", e))?;
        let pvk = prepare_verifying_key(&vk);

        let proof_bytes = hex::decode(&self.ivc_proof_bytes)
            .map_err(|e| format!("proof hex: {}", e))?;
        let proof = ark_groth16::Proof::<Bn254>::deserialize_compressed(proof_bytes.as_slice())
            .map_err(|e| format!("proof deser: {:?}", e))?;

        let init_fr  = Fr::deserialize_compressed(hex::decode(&self.initial_model_hash)
            .map_err(|e| format!("init hex: {}", e))?.as_slice())
            .map_err(|e| format!("init Fr: {:?}", e))?;
        let final_fr = Fr::deserialize_compressed(hex::decode(&self.final_model_hash)
            .map_err(|e| format!("final hex: {}", e))?.as_slice())
            .map_err(|e| format!("final Fr: {:?}", e))?;
        let chain_fr = Fr::deserialize_compressed(hex::decode(&self.proof_chain_hash)
            .map_err(|e| format!("chain hex: {}", e))?.as_slice())
            .map_err(|e| format!("chain Fr: {:?}", e))?;

        let public_inputs = vec![init_fr, final_fr, Fr::from(self.total_rounds), chain_fr];

        Groth16::<Bn254>::verify_with_processed_vk(&pvk, &public_inputs, &proof)
            .map_err(|e| format!("Groth16 IVC verify (pinned VK): {:?}", e))
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::round_prover::FLRoundProver;
    use ark_bn254::Fr;
    use std::env;

    fn temp_ivc_keys_dir(label: &str) -> PathBuf {
        let dir = env::temp_dir()
            .join(format!("ivc_keys_{}_{}", label, std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_ivc_accumulation_3_rounds() {
        let norm_bound    = 1.0_f64;
        let prover        = FLRoundProver::setup(norm_bound).expect("setup");
        let initial_hash  = Fr::from(0u64);
        let mut state     = IVCState::new(&initial_hash);

        let mut prev_hash = initial_hash;
        for i in 0u64..3 {
            let g = 0.05 * (i + 1) as f64;
            let grads = vec![g, -g * 0.5, g * 0.3];
            let grad_root = format!("grad_root_{}", i).into_bytes();
            let norm_bytes = format!("norm_proof_{}", i).into_bytes();

            let proof = prover.prove_round(
                i, prev_hash, &grads, norm_bound, 3,
                &grad_root, &norm_bytes,
            ).expect("prove_round");

            prev_hash = Fr::deserialize_compressed(
                hex::decode(&proof.new_model_hash).unwrap().as_slice()
            ).unwrap();

            state.fold_round(proof).expect("fold_round");
        }
        assert_eq!(state.round, 3);

        // Generate IVC keys (would normally be loaded from disk).
        let keys_dir = temp_ivc_keys_dir("3rounds");
        let keys = IVCKeys::setup_and_save(&keys_dir).expect("ivc setup");

        let final_proof = state.finalize_with_keys(&keys).expect("finalize");
        assert_eq!(final_proof.total_rounds, 3);
        println!("IVC anchor: {}", final_proof.on_chain_anchor);

        // Verify with embedded VK (unit test).
        let valid = final_proof.verify().expect("verify");
        assert!(valid, "IVC summary proof must be valid");

        // Verify with pinned VK (simulates on-chain flow).
        let pinned_hex = keys.vk_hex();
        let valid2 = final_proof.verify_with_pinned_vk(&pinned_hex).expect("verify pinned");
        assert!(valid2, "IVC proof must verify against pinned VK");

        // Cleanup.
        let _ = std::fs::remove_dir_all(&keys_dir);
    }

    #[test]
    fn test_ivc_padding_invariant() {
        // Two runs with different N should both verify against the same VK (Fix 6).
        let norm_bound  = 1.0_f64;
        let prover      = FLRoundProver::setup(norm_bound).expect("setup");
        let initial_hash = Fr::from(0u64);

        let make_state = |n_rounds: u64| {
            let mut state = IVCState::new(&initial_hash);
            let mut prev  = initial_hash;
            for i in 0..n_rounds {
                let grads = vec![0.01 * (i + 1) as f64];
                let proof = prover.prove_round(
                    i, prev, &grads, norm_bound, 1,
                    b"root", b"norm",
                ).unwrap();
                prev = Fr::deserialize_compressed(
                    hex::decode(&proof.new_model_hash).unwrap().as_slice()
                ).unwrap();
                state.fold_round(proof).unwrap();
            }
            state
        };

        let state1 = make_state(1);
        let state2 = make_state(2);
        let keys_dir = temp_ivc_keys_dir("padding");
        let keys = IVCKeys::setup_and_save(&keys_dir).expect("setup");

        let ivc1 = state1.finalize_with_keys(&keys).unwrap();
        let ivc2 = state2.finalize_with_keys(&keys).unwrap();

        // Both must verify individually with the SAME VK (Fix 6).
        assert!(ivc1.verify().unwrap(), "1-round IVC must verify");
        assert!(ivc2.verify().unwrap(), "2-round IVC must verify");

        // Their anchors must differ (different histories).
        assert_ne!(ivc1.on_chain_anchor, ivc2.on_chain_anchor);

        let _ = std::fs::remove_dir_all(&keys_dir);
    }
}
