name = "ransika/zkfl_cardano"
version = "0.0.1"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Recursive Verifiable Federated Learning on Cardano"

[repository]
user = "ransika"
project = "zkfl_cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
